### ISSUE TITLE
test REST generator

### ISSUE THREAD

**Issue by leondz** [leondz/garak#337]
* test the example
* set up a server for listening; look at the requests we get
* get the server to respond; see that rest generator parses output correctly

**Comment by aronzvi** [comment]
I'm trying to run the rest generator with garak v0.9.0.10.post1 and am encountering an issue.  

`python3 -m garak --version`.  
garak LLM security probe v0.9.0.10.post1


I use the resources/restdemo.json:`.  
 python3 -m garak --model_type rest -G restdemo.json`.  

and get the following error:    

garak LLM security probe v0.9.0.10.post1 ( https://github.com/leondz/garak ) at 2024-01-01T21:52:15.498921
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/garak/__main__.py", line 13, in <module>
    main()
  File "/opt/homebrew/lib/python3.11/site-packages/garak/__main__.py", line 9, in main
    cli.main(sys.argv[1:])
  File "/opt/homebrew/lib/python3.11/site-packages/garak/cli.py", line 365, in main
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/garak/cli.py", line 360, in main
    generator_cli_config = json.loads(generator_options_json)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 5 (char 157).  

I remove the comma at the end of line "X-Authorization": "$KEY" line to continue and rerun -     
`python3 -m garak --model_type rest -G restdemo.json`.  

and get the following error:    

garak LLM security probe v0.9.0.10.post1 ( https://github.com/leondz/garak ) at 2024-01-01T21:54:06.976405
📜 reporting to runs/garak.6cf8f289-6374-44dc-b512-dc902075bae3.report.jsonl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/garak/__main__.py", line 13, in <module>
    main()
  File "/opt/homebrew/lib/python3.11/site-packages/garak/__main__.py", line 9, in main
    cli.main(sys.argv[1:])
  File "/opt/homebrew/lib/python3.11/site-packages/garak/cli.py", line 441, in main
    generator = getattr(generator_mod, generator_class_name)(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/garak/generators/rest.py", line 147, in __init__
    raise ValueError(
**ValueError: No REST endpoint URI definition found in either constructor param, JSON, or --model_name. Please specify one.**


looking a bit into generators/rest.py:   
line 115 --     
`if "rest" in dir(_config.plugins.generators): `.  

_config.plugins.generators is a merged dict of our passed json. As far as I can tell, there is no "rest" property in the _config.plugins.generators and therefore none of the attributes will get set

**Comment by leondz** [comment]
Thanks for this. Both issues are now fixed:

1. resolved in #332

2. resolved in c9417adccae392d0ceb4f4771f1a6973ad84fd78
