### ISSUE TITLE
openai 1.x generator doesn't work nice with `parallel_attempts`

### ISSUE THREAD

**Issue by leondz** [leondz/garak#493]
see
```
(garak) 10:48:53 x1:~/dev_ext/garak [feature/oai_model_update] $ python3 -m garak -p dan.DanInTheWild -m openai -n gpt-4-turbo-preview -g 1 --parallel_attempts 20
garak LLM security probe v0.9.0.11.post2 ( https://github.com/leondz/garak ) at 2024-02-20T10:49:00.692318
📜 reporting to garak_runs/garak.cb7f7e26-3bc0-45b3-a95c-4615a6685ce2.report.jsonl
🦜 loading generator: OpenAI: gpt-4-turbo-preview
🕵️  queue of probes: dan.DanInTheWild
probes.dan.DanInTheWild:   0%|                                                                                                                                                            | 0/666 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/lderczynski/dev_ext/garak/garak/__main__.py", line 13, in <module>
    main()
  File "/home/lderczynski/dev_ext/garak/garak/__main__.py", line 9, in main
    cli.main(sys.argv[1:])
  File "/home/lderczynski/dev_ext/garak/garak/cli.py", line 477, in main
    command.probewise_run(generator, probe_names, evaluator, buffs)
  File "/home/lderczynski/dev_ext/garak/garak/command.py", line 216, in probewise_run
    probewise_h.run(generator, probe_names, evaluator, buffs)
  File "/home/lderczynski/dev_ext/garak/garak/harnesses/probewise.py", line 108, in run
    h.run(model, [probe], detectors, evaluator, announce_probe=False)
  File "/home/lderczynski/dev_ext/garak/garak/harnesses/base.py", line 92, in run
    attempt_results = probe.probe(model)
                      ^^^^^^^^^^^^^^^^^^
  File "/home/lderczynski/dev_ext/garak/garak/probes/base.py", line 131, in probe
    for result in attempt_pool.imap_unordered(
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lderczynski/anaconda3/envs/garak/lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object
```

contributing factors:
* `openai` module 1.x contains `_thread.RLock`
* `multiprocessing` uses `pickle`
* `pickle` can't handle `_thread.RLock`
* `base.probe()` links the generator in `self.generator`

possible mitigations:
* get the openai generator to work out if its being pickled, and avoid that
* use something other than `pickle`
* don't try to pickle the generator
* don't try to pickle this generator - maybe have a flag for generators that support parallelism (and hope these don't go stale? maybe a test that looks for exceptions in generators that are tagged non-parallelisable?)

possible upgrades:
* detect parallelisation failures and fall back to no parallelism, instead of exploding

**Comment by leondz** [comment]
Looks like this will be a wontfix from OpenAI's side: https://github.com/openai/openai-python/issues/837

Alternatives
1. pare apart the generator contents and do some pass-by-reference or similar to avoid duplicating generator objects when doing parallel probing
2. develop a shadow class, perhaps inheriting `RestGenerator`, that interfaces with OpenAI directly and is still `pickle`-able
3. move away from multiprocessing towards e.g. [`ray`](https://www.ray.io/)
4. try changing multiprocessing manager from `pickle` to `xmlrpclib` - https://docs.python.org/3/library/multiprocessing.html#multiprocessing.managers.BaseManager

All of these make some sense. 

Re: 1 - we should be efficient and not duplicate objects needlessly. 

Re: 2 - doing this in-house affords both tight control, and also helps us retain the generator abstraction (which custom `openai` lib-dependent changes might threaten). Could also be used with e.g. NVCF (see #559), or anything else compatible with the `openai` interface. 

Re: 3 - this library has a reputation for being slow and is a bit unpopular; it's not always super-intuitive to work with, and non-pickle serialisation options are always good. 

Re: 4 - I mean if it works..
