### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by DavidLee528** [leondz/garak#632]
Command and output:

```bash
root@AI_Server:/home/sda/tianhaoli/AVDS#  cd /home/sda/tianhaoli/AVDS ; /usr/bin/env /root/anaconda3/envs/garak310/bin/python /root/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 34521 -- /home/sda/tianhaoli/AVDS/app/garak/__main__.py --model_type huggingface --model_name meta-llama/Llama-2-7b-hf --probes malwaregen 
garak LLM security probe v0.9.0.12.post1 ( https://github.com/leondz/garak ) at 2024-04-26T20:51:55.930111
📜 reporting to garak_runs/garak.b8f03591-73a8-4bda-b9b2-b7fa6f230355.report.jsonl
🦜 loading generator: Hugging Face 🤗 pipeline: meta-llama/Llama-2-7b-hf
2024-04-26 20:52:29.567091: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-26 20:52:29.607328: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-26 20:52:34.258439: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.19s/it]
🕵️  queue of probes: malwaregen.Evasion, malwaregen.Payload, malwaregen.SubFunctions, malwaregen.TopLevel
probes.malwaregen.Evasion:   0%|                                                                                                               | 0/48 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
probes.malwaregen.Evasion:   2%|██▏                                                                                                    | 1/48 [00:03<02:21,  3.01s/it]--- Logging error ---
Traceback (most recent call last):
  File "/root/anaconda3/envs/garak310/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/root/anaconda3/envs/garak310/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/root/anaconda3/envs/garak310/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/root/anaconda3/envs/garak310/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/root/anaconda3/envs/garak310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/garak310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.4.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/sda/tianhaoli/AVDS/app/garak/__main__.py", line 15, in <module>
    main()
  File "/home/sda/tianhaoli/AVDS/app/garak/__main__.py", line 11, in main
    cli.main(sys.argv[1:])
  File "/home/sda/tianhaoli/AVDS/app/garak/cli.py", line 486, in main
    command.probewise_run(generator, probe_names, evaluator, buff_names)
  File "/home/sda/tianhaoli/AVDS/app/garak/command.py", line 212, in probewise_run
    probewise_h.run(generator, probe_names, evaluator, buffs)
  File "/home/sda/tianhaoli/AVDS/app/garak/harnesses/probewise.py", line 106, in run
    h.run(model, [probe], detectors, evaluator, announce_probe=False)
  File "/home/sda/tianhaoli/AVDS/app/garak/harnesses/base.py", line 93, in run
    attempt_results = probe.probe(model)
  File "/home/sda/tianhaoli/AVDS/app/garak/probes/base.py", line 189, in probe
    attempts_completed.append(self._execute_attempt(this_attempt))
  File "/home/sda/tianhaoli/AVDS/app/garak/probes/base.py", line 138, in _execute_attempt
    this_attempt.outputs = self.generator.generate(this_attempt.prompt)
  File "/home/sda/tianhaoli/AVDS/app/garak/generators/base.py", line 91, in generate
    return self._call_model(prompt, generations_this_call)
  File "/home/sda/tianhaoli/AVDS/app/garak/generators/huggingface.py", line 104, in _call_model
    raw_output = self.generator(
  File "/root/anaconda3/envs/garak310/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 240, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/root/anaconda3/envs/garak310/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1167, in __call__
    logger.warning_once(
  File "/root/anaconda3/envs/garak310/lib/python3.10/site-packages/transformers/utils/logging.py", line 329, in warning_once
    self.warning(*args, **kwargs)
Message: 'You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset'
Arguments: (<class 'UserWarning'>,)
malwaregen.Evasion                                                                malwaregen.AnyCode: SKIP  ok on    0/   0                                           
malwaregen.Payload                                                                malwaregen.AnyCode: SKIP  ok on    0/   0                                           
malwaregen.SubFunctions                                                           malwaregen.AnyCode: SKIP  ok on    0/   0                                           
malwaregen.TopLevel                                                               malwaregen.AnyCode: SKIP  ok on    0/   0                                           
📜 report closed :) garak_runs/garak.b8f03591-73a8-4bda-b9b2-b7fa6f230355.report.jsonl
📜 report html summary being written to garak_runs/garak.b8f03591-73a8-4bda-b9b2-b7fa6f230355.report.html
✔️  garak run complete in 191.72s
```

**Comment by DavidLee528** [comment]
Cause by error in third-party module:

https://github.com/huggingface/transformers/commit/c82b38a3e2c8af69fef08e371189766a87ed6159

**Comment by leondz** [comment]
quickfix is to upgrade transformers >= 4.40.0, e.g.

`python3 -m pip install "transformers>=4.40.0"`
