### ISSUE TITLE
bug: leakreplay not setting prompt in `attempt` as expected

### ISSUE THREAD

**Issue by leondz** [leondz/garak#788]
```
Traceback (most recent call last):                                                                                                                                    
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/x/.local/lib/python3.10/site-packages/garak/__main__.py", line 13, in <module>
    main()
  File "/home/x/.local/lib/python3.10/site-packages/garak/__main__.py", line 9, in main
    cli.main(sys.argv[1:])
  File "/home/x/.local/lib/python3.10/site-packages/garak/cli.py", line 499, in main
    command.probewise_run(
  File "/home/x/.local/lib/python3.10/site-packages/garak/command.py", line 218, in probewise_run
    probewise_h.run(generator, probe_names, evaluator, buffs)
  File "/home/x/.local/lib/python3.10/site-packages/garak/harnesses/probewise.py", line 107, in run
    h.run(model, [probe], detectors, evaluator, announce_probe=False)
  File "/home/x/.local/lib/python3.10/site-packages/garak/harnesses/base.py", line 108, in run
    attempt_results = probe.probe(model)
  File "/home/x/.local/lib/python3.10/site-packages/garak/probes/base.py", line 210, in probe
    attempts_completed = self._execute_all(attempts_todo)
  File "/home/x/.local/lib/python3.10/site-packages/garak/probes/base.py", line 188, in _execute_all
    result = self._execute_attempt(this_attempt)
  File "/home/x/.local/lib/python3.10/site-packages/garak/probes/base.py", line 152, in _execute_attempt
    this_attempt = self._postprocess_hook(this_attempt)
  File "/home/x/.local/lib/python3.10/site-packages/garak/probes/leakreplay.py", line 67, in _postprocess_hook
    attempt.outputs = [re.sub("</?name>", "", o) for o in attempt.outputs]
  File "/home/x/.local/lib/python3.10/site-packages/garak/attempt.py", line 185, in __setattr__
    raise TypeError("A prompt must be set before outputs are given")
TypeError: A prompt must be set before outputs are given
```

**Comment by leondz** [comment]
resolved in #790
