### ISSUE TITLE
`load_plugin` should support generators

### ISSUE THREAD

**Issue by leondz** [leondz/garak#926]
## Summary

`garak._plugins.load_plugin()` supports most plugins but not generators. Instead, generator-specific prep is embedded into `garak.cli`. This isn't a sensible canonical location for generator-loading code. The logic for loading generators should be moved out. There's already a standard point for spinning up plugins - let's re-use that.

### Basic example

```
import garak._plugins
c = {"plugins": {"model_type": "openai", "model_name":"gpt-4"}}
g = _plugins.load_module("generators.openai", config_root=c)
```

This may involve better handling the `name` param in generator constructors - or even removing it.

This is where we currently are (slightly different config but hey):

```
>>> c = {"plugins":{"generators":{'openai': {'name': 'gpt-4'}}}}
>>> import garak
>>> import garak._plugins
>>> g = garak._plugins.load_plugin("generators.openai", config_root=c)
WARNING:root:Exception instantiating garak.generators.openai.OpenAIGenerator: 'dict' object has no attribute 'plugins'
Traceback (most recent call last):
  File "/home/lderczynski/dev/garak/garak/_plugins.py", line 390, in load_plugin
    plugin_instance = klass(config_root=config_root)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lderczynski/dev/garak/garak/generators/openai.py", line 315, in __init__
    super().__init__(self.name, config_root=config_root)
  File "/home/lderczynski/dev/garak/garak/generators/openai.py", line 158, in __init__
    print(config_root.plugins.generators)
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'plugins'
Traceback (most recent call last):
  File "/home/lderczynski/dev/garak/garak/_plugins.py", line 390, in load_plugin
    plugin_instance = klass(config_root=config_root)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lderczynski/dev/garak/garak/generators/openai.py", line 315, in __init__
    super().__init__(self.name, config_root=config_root)
  File "/home/lderczynski/dev/garak/garak/generators/openai.py", line 158, in __init__
    print(config_root.plugins.generators)
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'plugins'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lderczynski/dev/garak/garak/_plugins.py", line 400, in load_plugin
    raise GarakException(e) from e
garak.exception.GarakException: 'dict' object has no attribute 'plugins'
```

### Motivation

This supports simpler maintenance and loading of generator instantiation, by placing the logic in one location, and removing generator spin-up logic - including conditioning based on the requested module - from `garak.cli`. 

We also have some difficulty loading generators from places other than `garak.cli`, depending on the generator; improving this makes probes and detectors more powerful in the range of what generators they can use. For example, LLMaaJ #419  works well with GPT-4, but writing this in a detector means some logic duplication.

**Comment by jmartin-tech** [comment]
Let refactor this to clarify format for a `configurable` object when parsing `config_root` as a `dict`.
