### ISSUE TITLE
ZeroDivisionError in garak/harnesses/probewise.py

### ISSUE THREAD

**Issue by evilsocket** [leondz/garak#941]
## Steps to reproduce

How'd you do it?

1. garak --model_type huggingface --model_name gpt2

Literally the first time I try this tool.

## Were you following a specific guide/tutorial or reading documentation?

nope, just tried to run it on gpt2

## Expected behavior

It should complete without errors.

## Current behavior

```
Tree search nodes traversed:   4%|██████▍                                                                                                                                             | 1/23 [00:00<00:00, 318.26it/s]Traceback (most recent call last):                                                                                                                                                                                    
  File "/home/simone/.local/bin/garak", line 8, in <module>
    sys.exit(main())
  File "/home/simone/.local/lib/python3.10/site-packages/garak/__main__.py", line 9, in main
    cli.main(sys.argv[1:])
  File "/home/simone/.local/lib/python3.10/site-packages/garak/cli.py", line 509, in main
    command.probewise_run(
  File "/home/simone/.local/lib/python3.10/site-packages/garak/command.py", line 222, in probewise_run
    probewise_h.run(generator, probe_names, evaluator, buffs)
  File "/home/simone/.local/lib/python3.10/site-packages/garak/harnesses/probewise.py", line 107, in run
    h.run(model, [probe], detectors, evaluator, announce_probe=False)
  File "/home/simone/.local/lib/python3.10/site-packages/garak/harnesses/base.py", line 108, in run
    attempt_results = probe.probe(model)
  File "/home/simone/.local/lib/python3.10/site-packages/garak/probes/base.py", line 366, in probe
    mean_score = sum(node_results) / len(node_results)
ZeroDivisionError: division by zero
```

### garak version

v0.9.0.16

## Additional Information

1. Ubuntu 22.04.2 LTS on x86_64
2. Python version3.10.12
3. Install method pip
4. Logs from execution: garak.log attached [garak.log](https://github.com/user-attachments/files/17280932/garak.log)
5. Details of execution config: literally just `garak --model_type huggingface --model_name gpt2`
6. Any relevant hardware or resource information: not really

**Comment by evilsocket** [comment]
thank *you* for this amazing tool

**Comment by erickgalinkin** [comment]
Thanks for the report Simone! Good to see you again! I've opened a PR to address this.
